name: Build and deploy docker image

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
    Build_and_publish_dahliaOS_buildroot_docker_image:
        runs-on: ubuntu-latest
        steps:
          - name: 'Checkout GitHub Action'
            uses: actions/checkout@main
            
          - name: 'Login to GitHub Container Registry'
            uses: docker/login-action@v2.1.0
            with:
              registry: ghcr.io
              username: ${{github.actor}}
              password: ${{secrets.GITHUB_TOKEN}}
              
          - name: 'Build Docker Image'
            run: |
             docker build . --tag ghcr.io/dahliaos/buildroot:latest
             docker run ghcr.io/dahliaos/buildroot:latest
             docker push ghcr.io/dahliaos/buildroot:latest
